server:
  port: 8080

spring:
  application:
    name: REST_API
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/newdy
    username: testuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 400
        use_sql_comments: true
    open-in-view: false