
server:
  port: 8080

spring:
  application:
    name: REST_API
  profiles:
    active: test # default
    group:
      local:
        - common
      test:
        - common

---
#spring.config.activate.on-profile:local

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/newdy
    username: testuser
    password: 1234
    p6spy:
      # JDBC 이벤트 로깅을 위한 P6LogFactory 등록
      enable-logging: true
      # com.p6spy.engine.spy.appender.MultiLineFormat 사용 (SingleLineFormat 대신)
      multiline: true
      # 기본 리스너들을 위한 로깅 사용 [slf4j, sysout, file, custom]
      logging: slf4j
      # 실제 값으로 '?'를 대체한 효과적인 SQL 문자열을 추적 시스템에 보고
      # 참고: 이 설정은 로깅 메시지에 영향을 주지 않음
      tracing:
        include-parameter-values: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 400
        use_sql_comments: true
    open-in-view: false
    data:
      web:
        pageable:
          default-page-size: 10
          max-page-size: 50

---

  #spring.config.activate.on-profile:common

spring:
  config:
    activate:
      on-profile: common
  jwt:
    header: Authorization
    secret: ZXJzdFJlc3RBUElBcHBsaWNhdGlvbg==


---

  #spring.config.activate.on-profile:test

spring:
  config:
    activate:
      on-profile: test
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:
    p6spy:
      # JDBC 이벤트 로깅을 위한 P6LogFactory 등록
      enable-logging: true
      # com.p6spy.engine.spy.appender.MultiLineFormat 사용 (SingleLineFormat 대신)
      multiline: true
      # 기본 리스너들을 위한 로깅 사용 [slf4j, sysout, file, custom]
      logging: slf4j
      # 실제 값으로 '?'를 대체한 효과적인 SQL 문자열을 추적 시스템에 보고
      # 참고: 이 설정은 로깅 메시지에 영향을 주지 않음
      tracing:
        include-parameter-values: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 400
        use_sql_comments: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50



#server:
#  port: 8080
#
#spring:
#  application:
#    name: REST_API
#  jwt:
#    header: Authorization
#    secret: ZXJzdFJlc3RBUElBcHBsaWNhdGlvbg==
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:postgresql://localhost:5432/newdy
#    username: testuser
#    password: 1234
#    p6spy:
#      # JDBC 이벤트 로깅을 위한 P6LogFactory 등록
#      enable-logging: true
#
#      # com.p6spy.engine.spy.appender.MultiLineFormat 사용 (SingleLineFormat 대신)
#      multiline: true
#
#      # 기본 리스너들을 위한 로깅 사용 [slf4j, sysout, file, custom]
#      logging: slf4j
#
#      # 실제 값으로 '?'를 대체한 효과적인 SQL 문자열을 추적 시스템에 보고
#      # 참고: 이 설정은 로깅 메시지에 영향을 주지 않음
#      tracing:
#        include-parameter-values: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        default_batch_fetch_size: 400
#        use_sql_comments: true
#    open-in-view: false
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 50
#
